# The one writer into applications/. Runs when the person clicks Mark applied,
# never otherwise, so the archive fills with real applications rather than with
# drafts for jobs they skipped.
class ApplicationArchiver
  def self.call(...) = new(...).call

  def initialize(job_posting)
    @posting = job_posting
  end

  def call
    return nil unless dir.exist?

    File.write(path, contents)
    path
  end

  def path
    date = (@posting.applied_at || Time.current).to_date.iso8601
    dir.join("#{date}-#{@posting.slug}.md")
  end

  private

  def dir = Radar.career_path.join("applications")

  def proposal = @posting.latest_proposal

  def contents
    <<~MD
      # Application: #{@posting.title}

      - **Date:** #{(@posting.applied_at || Time.current).to_date.iso8601}
      - **Source:** Upwork
      - **Link:** #{@posting.upwork_url}
      - **Status:** sent
      - **Rate proposed:** #{@posting.rate_proposed.presence || 'not recorded'}

      ## Job post

      #{@posting.description}

      ## Cover letter (final, ready to paste)

      ```
      #{proposal&.body}
      ```

      ## Notes / follow-up

      - Generated by Upwork Radar#{proposal&.template_name.present? ? " using template `#{proposal.template_name}`" : ''}.
      - Match score #{@posting.score}/100.#{proposal && proposal.version > 1 ? " Regenerated #{proposal.version - 1} time(s) before sending." : ''}
    MD
  end
end
